### PR TITLE
Add support for CancellationTokens within client and services methods.

### PR DESCRIPTION
**Pull request by AhmedZaki99**
This one is a little bigger than usual.

Since [`HttpClient`](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient) supports optional [`CancellationToken`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken) in its methods, `TodoistRestClient` can be changed to accept cancellation tokens and pass them to `HttpClient` method calls.

**First, important things to consider:**

1. Changes to [`TodoistRestClient`](https://github.com/olsh/todoist-net/blob/master/src/Todoist.Net/TodoistRestClient.cs) should not affect consumers of that class, so the `CancellationToken` must be optional.
2. Any changes to the [`ITodoistRestClient`](https://github.com/olsh/todoist-net/blob/master/src/Todoist.Net/ITodoistRestClient.cs) interface would break classes that implement it, so the interface should remain unchanged.

Based on those constraints, to accept the optional `CancellationToken`, an [`ICancellableTodoistRestClient`](https://github.com/AhmedZaki99/todoist-net/blob/patch-2/src/Todoist.Net/ICancellableTodoistRestClient.cs) interface is added that inherits from `ITodoistRestClient` and extends it with method overloads that accept the `CancellationToken` parameter.
`TodoistRestClient` is then changed to implement `ICancellableTodoistRestClient` and support cancellation.

Second, cancellation tokens are like async methods; they are “contagious” all the way down the method call chain. This means in order to utilize the usage of cancellation tokens added to `TodoistRestClient`, then [`TodoistClient`](https://github.com/olsh/todoist-net/blob/master/src/Todoist.Net/TodoistClient.cs), [`TodoistTokenlessClient`](https://github.com/olsh/todoist-net/blob/master/src/Todoist.Net/TodoistTokenlessClient.cs), and all services that depend on them need to have optional `CancellationToken` parameter in their methods as well.

**Changes then were too many so they were split into four commits to become easy to review:**

1. Duplicate documentation comments were replaced by [`<inheritdoc>`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#inheritdoc) tag so they change dynamically when `CancellationToken` parameters are added to interfaces.
2. The `ICancellableTodoistRestClient` is added along with the `TodoistRestClient` implementation for it.
3. `TodoistClient` is updated to support cancellation by checking if the [`_restClient`](https://github.com/olsh/todoist-net/blob/75642f4ca6b2cb29e77dcacfe5b7225d245a6030/src/Todoist.Net/TodoistClient.cs#L31) field implements `ICancellableTodoistRestClient` and then passes the `CancellationToken` to it.
4. All other services that depend on the `TodoistClient` are updated to accept cancellation tokens and pass them to `TodoistClient` methods.

I hope you find this contribution useful and not too hard to review.

### CODE REVIEW

**Comment by AhmedZaki99** [comment]
**One extra change has been committed:**
A constructor overload for `TodoistClient` has been added that accepts an `ICancellableTodoistRestClient` argument, to explicitly state that the `TodoistClient` can be instantiated using a cancellable client implementation.

This change is not necessarily part of the proposed contribution, it's just a design change. It's up to you to include it in the merge if you accept the pull request.

**Comment by olsh** [comment]
Thank you for the contibution 👍🏻 
I'll take a look a bit later.

**Comment by olsh** [comment]
> Any changes to the [ITodoistRestClient](https://github.com/olsh/todoist-net/blob/master/src/Todoist.Net/ITodoistRestClient.cs) interface would break classes that implement it, so the interface should remain unchanged.

In this case I'd choose breaking changes over introducing a new interface.
I suggest that we just increase the library version and add cancellation token parameter to [ITodoistRestClient](https://github.com/olsh/todoist-net/blob/master/src/Todoist.Net/ITodoistRestClient.cs) and delete `ICancellableTodoistRestClient`.

**Comment by AhmedZaki99** [comment]
Ok, I will add a commit with these changes.

**Comment by AhmedZaki99** [comment]
`ITodoistRestClient` now supports cancellation tokens directly, and implementing classes like `Todoist.Net.TodoistRestClient` and `Todoist.Net.Tests.RateLimitAwareRestClient` has been changed accordingly.

**Pull request merged**
