### PR TITLE
Added new overload for getResources that supports passing in sync token

### PR DESCRIPTION
**Pull request by AlexGirardDev**
Just adding incremental sync support to client

I didn't bother adding it for all the individual services as I didn't need it but it should be a pretty easy add if desired.

### CODE REVIEW

**Comment by olsh** [comment]
Thank you for your contribution! 👍🏻

**Comment by AlexGirardDev** [comment]
No Problem, I appreciate the work you did on this library and its been very useful to me 💯.

I was wondering if you planned to cut a release with these changes, I would love to just be able to use the nuget package with my changes 😄

**Comment by olsh** [comment]
The update was published in [v3.0.0](https://github.com/olsh/todoist-net/releases/tag/3.0.0) and available on [NuGet](https://www.nuget.org/packages/Todoist.Net/3.0.0)

**Comment by AlexGirardDev** [comment]
Awesome, thanks so much.

**Pull request merged**
