### PR TITLE
added text option

### PR DESCRIPTION
**Pull request by yonka2019**
added option to set text and datetime to duedate of item.

This could be used when recurring needed from X date.
'every day from X' isn't really enables recurring, there is a bug.

### CODE REVIEW

**Comment by olsh** [comment]
Hi @yonka2019 

Thank you for your contribution.
Could we update this overload by adding the optional `DateTime? date = null` parameter?
https://github.com/olsh/todoist-net/blob/main/src/Todoist.Net/Models/DueDate.cs#L43-L54

Like this
```csharp
        public DueDate(string text, DateTime? date = null, string timezone = null, Language language = null)
        {
            Text = text;
            Timezone = timezone;
            Language = language;
            Date = date;
        }
```
What do you think?

Also, I believe that the overload needs more clear comments, especially about the text and date parameters.

**Comment by yonka2019** [comment]
yeah I think it would be better.
Where do you mean to add more comments? at the code? or at the commit description

**Comment by olsh** [comment]
> Where do you mean to add more comments? at the code? or at the commit description

Yes, I meant comments in the code.

**Review by olsh — CHANGES_REQUESTED** [review]
Could you please fix the build?

**Comment by olsh** [comment]
@yonka2019 
I've just tried to reproduce the initial issue

> This could be used when recurring needed from X date.
> 'every day from X' isn't really enables recurring, there is a bug.

And it looks like it works, here is the code

```csharp
            var item = new Item("demo task") { DueDate = new DueDate("Every day from 20 Apr", language: Language.English) };
            await client.Items.AddAsync(item).ConfigureAwait(false);
```

Could you please send me the code that reproduces the issues?

**Comment by yonka2019** [comment]
> Could you please send me the code that reproduces the issue?

yeah, I changed the due date to already created item (shifted the date by one, and added recurring of every 3 days.
for example: 
`task.DueDate = new DueDate($"{task.DueDate.Date.Value.AddDays(1).ToShortDateString().Replace(".", "/")} every 3 days");`
'// 03/04/2023 every 3 days'

the todoist shows like the recurring is enabled, but really - when you marking the task as done, it doesn't re-creates her-self.

**Comment by olsh** [comment]
Yeah, managed to reproduce the issue.

@yonka2019 
I've slightly changed the final constructor, not sure if `isFullDay` parameter makes any sense when using text for due date creation.
Please let me know what you think.

**Comment by yonka2019** [comment]
> I've slightly changed the final constructor, not sure if `isFullDay` parameter makes any sense when using text for due date creation.
> Please let me know what you think.

it makes sense because without that, it will start from X date 21:00

**Comment by olsh** [comment]
> it makes sense because without that, it will start from X date 21:00

Got it. Thank you for your contribution.

**Pull request merged**
